version: 0.2
phases:   
  build: 
    commands: 
      - aws2 cloudformation package --template-file template.yaml --s3-bucket aws-team --output-template-file template-cfn.yaml
artifacts:
  type: zip
  files: 
    - template.yaml
    - template-cfn.yaml