AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A starter AWS Lambda function.
Resources:
  helloworldpython3:
    Type: 'AWS::Serverless::Function'
    Properties:
      AutoPublishAlias: Demolive
      FunctionName: DemoFunction
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./LambdaCode
      Description: A starter AWS Lambda function.
      MemorySize: 128
      Timeout: 60
      Events:
        Api:
          Type: Api
          Properties:
            Path: /dmo
            Method: put      